services:
  client-dev:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - SERVER_ID=dev
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3000
      - VITE_APP_NAME=Vite Dynamic Env - DEV
      - VITE_VERSION=1.0.0
      - VITE_DEBUG=true
    restart: unless-stopped

  client-staging:
    build: .
    ports:
      - "5174:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - SERVER_ID=staging
      - NODE_ENV=staging
      - VITE_API_URL=https://staging-api.example.com
      - VITE_APP_NAME=Vite Dynamic Env - STAGING
      - VITE_VERSION=1.0.0
      - VITE_DEBUG=false
    restart: unless-stopped

  client-prod:
    build: .
    ports:
      - "5175:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - SERVER_ID=prod
      - NODE_ENV=production
      - VITE_API_URL=https://api.example.com
      - VITE_APP_NAME=Vite Dynamic Env - PROD
      - VITE_VERSION=1.0.0
      - VITE_DEBUG=false
    restart: unless-stopped